
name: telegram-bots
language: python
port: 5000
install: pip install -r requirements.txt
build: echo "Build complete"
run: python unified_bot_launcher.py
environments:
  - PYTHONUNBUFFERED=1
  - BOT_MODE=production
